config/routes.rb
require 'override_csp'

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end

  direct :rails_public_blob do |blob|
    if Rails.env.development? || Rails.env.test? || ENV['CLOUDFRONT_HOST'].blank?
      route =
        if blob.is_a?(ActiveStorage::Variant) || blob.is_a?(ActiveStorage::VariantWithRecord)
          :rails_representation
        else
         :rails_blob
        end
      route_for(route, blob, only_path: true)
    else
      Cloudfront::GenerateSignedUrlService.new(blob).generate_url
    end
  end

  post '/graphql', to: 'graphql#execute'

  devise_for :users, only: %i[sessions omniauth_callbacks], controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    post 'users/send_reset_password_email', controller: 'users/sessions', action: 'send_reset_password_email', as: 'user_send_reset_password_email'
    get 'users/token', controller: 'users/sessions', action: 'token', as: 'user_token'
    get 'users/reset_password', controller: 'users/sessions', action: 'reset_password', as: 'reset_password'
    post 'users/update_password', controller: 'users/sessions', action: 'update_password', as: 'update_password'
    get 'users/sign_in_with_email', controller: 'users/sessions', action: 'sign_in_with_email', as: 'sign_in_with_email'
    get 'users/request_password_reset', controller: 'users/sessions', action: 'request_password_reset', as: 'request_password_reset'

    if Rails.env.development?
      get 'users/auth/developer', controller: 'users/omniauth_callbacks', action: 'passthru', as: 'user_developer_omniauth_authorize'
      post 'users/auth/developer/callback', controller: 'users/omniauth_callbacks', action: 'developer'
    end
  end

  get 'users/delete_account', controller: 'users', action: 'delete_account', as: 'delete_account'

  post 'users/email_bounce', controller: 'users/postmark_webhook', action: 'email_bounce'

  authenticate :user, ->(u) { AdminUser.where(email: u.email).present? } do
    mount Delayed::Web::Engine, at: '/jobs'
    mount OverrideCsp.new(Flipper::UI.app(Flipper)), at: '/toggle'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resource :applicants, only: [] do
    get '/:token', action: 'enroll' # TODO: Legacy route - remove after a few weeks.
    get '/:token/enroll', action: 'enroll', as: 'enroll'
  end

  resources :notifications, only: %i[show]

  resource :school, only: %i[show update] do
    get 'customize'
    get 'admins'
    post 'images'
  end

  namespace :school, module: 'schools' do
    resources :faculty, only: %i[create update destroy], as: 'coaches', path: 'coaches' do
      collection do
        get '/', action: 'school_index'
      end
    end

    resources :targets, only: [] do
      resource :content_block, only: %i[create]
    end

    resources :courses, only: %i[index show new] do
      member do
        get 'applicants'
        get 'details'
        get 'images', action: :details
        get 'actions', action: :details
        get 'curriculum'
        get 'exports'
        get 'authors'
        get 'certificates'
        post 'certificates', action: 'create_certificate'
        post 'bulk_import_students'
        get 'evaluation_criteria'
        post 'attach_images'
      end

      resources :authors, only: %w[show new]

      resources :applicants, only: :show do
        member do
          get 'actions', action: :show
          get 'details', action: :show
        end
      end

      resources :targets, only: [] do
        member do
          get 'content'
          get 'details'
          get 'versions'
        end
      end

      resources :levels, only: %i[create]

      resources :faculty, as: 'coaches', path: 'coaches', only: [] do
        collection do
          get '/', action: 'course_index'
        end
      end

      post 'mark_teams_active'
      get 'students'
      get 'inactive_students'
      post 'delete_coach_enrollment'
      post 'update_coach_enrollments'
    end

    resources :founders, as: 'students', path: 'students', except: %i[index] do
      collection do
        post 'team_up'
      end
    end

    resources :levels, only: %i[update] do
      resources :target_groups, only: %i[create]
    end

    resources :target_groups, only: %i[update]

    resources :communities, only: %i[index]
  end

  resources :communities, only: %i[show] do
    member do
      get 'new_topic'
      get ':name', action: 'show'
    end
  end

  get 'topics/:id(/:title)', controller: 'topics', action: 'show', as: 'topic'

  get 'posts/:id/versions', controller: 'posts', action: 'versions', as: 'post_version'

  get 'dashboard', controller: 'users', action: 'dashboard', as: 'dashboard'

  resource :user, only: %i[edit] do
    post 'upload_avatar'
  end

  resources :timeline_event_files, only: %i[create] do
    member do
      get 'download'
    end
  end

  resources :faculty, only: %i[] do
    collection do
      get 'filter/:active_tab', to: 'faculty#index'
      get 'weekly_slots/:token', to: 'faculty#weekly_slots', as: 'weekly_slots'
      post 'save_weekly_slots/:token', to: 'faculty#save_weekly_slots', as: 'save_weekly_slots'
      delete 'weekly_slots/:token', to: 'faculty#mark_unavailable', as: 'mark_unavailable'
      get 'slots_saved/:token', to: 'faculty#slots_saved', as: 'slots_saved'
    end
  end

  scope 'coaches', controller: 'faculty' do
    get '/', action: 'index', as: 'coaches_index'
    get '/:id(/:slug)', action: 'show', as: 'coach'
    get '/filter/:active_tab', action: 'index'
  end

  scope 'connect_request', controller: 'connect_request', as: 'connect_request' do
    get ':id/feedback/from_team/:token', action: 'feedback_from_team', as: 'feedback_from_team'
    get ':id/feedback/from_faculty/:token', action: 'feedback_from_faculty', as: 'feedback_from_faculty'
    get ':id/join_session(/:token)', action: 'join_session', as: 'join_session'
    patch ':id/feedback/comment/:token', action: 'comment_submit', as: 'comment_submit'
  end

  # Founder show
  scope 'students', controller: 'founders' do
    get '/:id/report', action: 'report', as: 'student_report'
  end

  get 'styleguide', to: 'home#styleguide', constraints: DevelopmentConstraint.new

  get 'manifest', to: 'home#manifest'
  get 'offline', to: 'home#offline'
  root 'home#index'

  # TODO: Remove this backwards-compatibility path after Jan 2021.
  get 'agreements/terms-of-use', to: redirect('/agreements/terms-and-conditions')

  get 'agreements/:agreement_type', as: 'agreement', controller: 'home', action: 'agreement'

  resources :targets, only: %i[show] do
    member do
      get 'details_v2'
      get ':slug', action: 'show'
    end
  end

  resources :timeline_events, only: %i[show], path: 'submissions' do
    member do
      get 'review', action: 'review'
    end
  end

  resources :courses, only: %i[show] do
    member do
      get 'review', action: 'review'
      get 'students', action: 'students'
      get 'leaderboard', action: 'leaderboard'
      get 'curriculum', action: 'curriculum'
      get 'report', action: 'report'
      get 'apply', action: 'apply'
      post 'apply', action: 'process_application'
      get '/(:name)', action: 'show'
    end
  end

  resources :markdown_attachments, only: %i[create] do
    member do
      get '/:token', action: 'download', as: 'download'
    end
  end

  get '/c/:serial_number', to: 'issued_certificates#verify', as: :issued_certificate
  get '/help/:document', to: 'help#show'
  get '/oauth/:provider', to: 'home#oauth', as: 'oauth', constraints: SsoConstraint.new
  get '/oauth_error', to: 'home#oauth_error', as: 'oauth_error'

  # Allow developers to simulate the error pages.
  get '/errors/:error_type', to: 'errors#simulate', constraints: DevelopmentConstraint.new

  get '/service-worker.js', to: 'home#service_worker'
  get '/favicon.ico', to: 'home#favicon'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  include RecaptchaVerifiable

  before_action :authenticate_user!,
                except: %i[show apply process_application curriculum]

  before_action :preview_or_authenticate, only: %i[curriculum]

  # GET /courses/:id/curriculum
  def curriculum
    @presenter = Courses::CurriculumPresenter.new(view_context, @course)
    render layout: 'student_course'
  end

  # GET /courses/:id/leaderboard?weeks_before=
  def leaderboard
    @course = authorize(find_course)
    @on = params[:on]
    render layout: 'student_course'
  end

  # GET /courses/:id/apply
  def apply
    @course = authorize(find_course)
    @show_checkbox_recaptcha = params[:visible_recaptcha].present?

    save_tag

    render layout: 'tailwind'
  end

  # POST /courses/:id/apply
  def process_application
    @course = authorize(find_course)

    form = Courses::EnrollmentForm.new(@course)

    recaptcha_success =
      recaptcha_success?(@form, action: 'public_course_enrollment')

    unless recaptcha_success
      redirect_to apply_course_path(params[:id], visible_recaptcha: 1)
      return
    end

    if form.validate(params)
      form.create_applicant(session)

      flash[:success] =
        "We've sent you a verification mail. It should reach you in less than a minute. Click the link in the email to sign up, and get started."

      redirect_to root_path
    else
      flash[:error] =
        "There were errors with your submission: #{form.errors.full_messages.join(', ')}"

      redirect_to apply_course_path(params[:id], visible_recaptcha: 1)
    end
  end

  # GET /courses/:id/(:slug)
  def show
    @course = authorize(find_course)
    render layout: 'student'
  end

  # GET /courses/:id/review
  def review
    @course = authorize(find_course)
    render html: '', layout: 'app_router'
  end

  # GET /courses/:id/students
  def students
    @course = authorize(find_course)
    render layout: 'student_course'
  end

  # GET /courses/:id/report
  def report
    @course = authorize(find_course)
    render layout: 'student_course'
  end

  private

  def preview_or_authenticate
    course = find_course

    authenticate_user! unless course.public_preview?

    @course = authorize(course)
  end

  def find_course
    policy_scope(Course).find(params[:id])
  end

  def save_tag
    return if params[:tag].blank?

    if params[:tag].in?(current_school.founder_tag_list)
      session[:applicant_tag] = params[:tag]
    end
  end
end

app/controllers/schools/courses_controller.rb
module Schools
  class CoursesController < SchoolsController
    include CamelizeKeys
    include StringifyIds

    layout 'school'

    # GET /school/courses
    def index
      authorize(current_school, policy_class: Schools::CoursePolicy)
    end

    # GET /school/course/new
    def new
      index
      render 'index'
    end

    # GET /school/course/id/
    def show
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
      redirect_to details_school_course_path
    end

    # GET /school/course/id/details
    def details
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
      render 'index'
    end

    # POST /courses/id/attach_images
    def attach_images
      course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
      @form = Schools::Courses::UpdateImagesForm.new(course)

      if @form.validate(params)
        @form.save
        render json: {
                 thumbnail_url: course.thumbnail_url,
                 cover_url: course.cover_url,
                 error: nil
               }
      else
        render json: {
                 thumbnail_url: nil,
                 cover_url: nil,
                 error: @form.errors.full_messages.join(', ')
               }
      end
    end

    # GET /courses/:id/curriculum
    def curriculum
      course =
        scope
          .includes(:evaluation_criteria, :levels, :target_groups, :targets)
          .find(params[:id])

      @course = authorize(course, policy_class: Schools::CoursePolicy)
    end

    # POST /school/courses/:course_id/delete_coach_enrollment
    def delete_coach_enrollment
      coach = current_school.faculty.find(params[:coach_id])
      course =
        authorize(
          scope.find(params[:course_id]),
          policy_class: Schools::CoursePolicy
        )

      ::Courses::UnassignReviewerService.new(course).unassign(coach)

      render json: { coach_id: coach.id.to_s, error: nil }
    end

    def update_coach_enrollments
      course =
        authorize(
          scope.find(params[:course_id]),
          policy_class: Schools::CoursePolicy
        )
      coaches =
        current_school.faculty.where(id: params[:coach_ids]).includes(:school)

      coaches.each do |coach|
        ::Courses::AssignReviewerService.new(course, notify: true).assign(coach)
      end

      course_coaches =
        coaches.map do |coach|
          {
            id: coach.id.to_s,
            name: coach.name,
            title: coach.title,
            email: coach.email,
            avatarUrl: coach.user.avatar_url(variant: :thumb)
          }
        end

      render json: { course_coaches: course_coaches, error: nil }
    end

    # GET /school/courses/:course_id/students
    def students
      @course =
        authorize(
          scope.find(params[:course_id]),
          policy_class: Schools::CoursePolicy
        )
    end

    # GET /school/courses/:id/applicants
    def applicants
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
    end

    def inactive_students
      @course =
        authorize(
          scope.find(params[:course_id]),
          policy_class: Schools::CoursePolicy
        )

      inactive_teams =
        if params[:search].present?
          ::Courses::InactiveTeamsSearchService
            .new(@course)
            .find_teams(params[:search].to_s)
        else
          Startup.joins(:course).inactive.where(courses: { id: @course }).to_a
        end

      @teams =
        Kaminari.paginate_array(inactive_teams).page(params[:page]).per(20)
    end

    # POST /school/courses/:course_id/mark_teams_active?team_ids[]=
    def mark_teams_active
      course =
        authorize(
          scope.find(params[:course_id]),
          policy_class: Schools::CoursePolicy
        )

      Startup.transaction do
        course
          .startups
          .where(id: params[:team_ids])
          .each do |startup|
            startup.update!(access_ends_at: nil, dropped_out_at: nil)
          end

        render json: {
                 message: 'Teams marked active successfully!',
                 error: nil
               }
      end
    end

    # GET /school/courses/:id/exports
    def exports
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
    end

    # GET /school/courses/:id/authors
    def authors
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
    end

    # GET /school/courses/:id/certificates
    def certificates
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
    end

    # POST /school/courses/:id/certificates
    def create_certificate
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)

      form = ::Courses::CreateCertificateForm.new(@course)

      props =
        if form.validate(params)
          scope = Certificate.where(id: form.save.id)
          ActiveRecord::Precounter.new(scope).precount(:issued_certificates)

          {
            error: nil,
            certificate:
              Schools::Courses::CertificatesPresenter.certificate_details(
                scope.first
              )
          }
        else
          { error: form.errors.full_messages.join(', ') }
        end

      render json: camelize_keys(stringify_ids(props))
    end

    # POST /school/courses/:id/bulk_import_students
    def bulk_import_students
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)

      form = ::Courses::BulkImportStudentsForm.new(@course)
      form.current_user = current_user

      props =
        if form.validate(params)
          form.save
          { success: true }
        else
          { error: form.errors.full_messages.join(', ') }
        end

      render json: camelize_keys(stringify_ids(props))
    end

    # GET /school/courses/:id/evaluation_criteria
    def evaluation_criteria
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
    end

    private

    def scope
      @scope ||=
        policy_scope(Course, policy_scope_class: Schools::CoursePolicy::Scope)
    end
  end
end

app/views/courses/_topper_avatar.html.erb
<div class="leaderboard__winner-avatar">
  <% if student.avatar.attached? %>
    <%= image_tag (student.avatar_variant(:thumb)), class: 'w-full object-contain' %>
  <% else %>
    <%= image_tag (student.initials_avatar), class: 'w-full object-contain' %>
  <% end %>
</div>

app/views/courses/apply.html.erb
<% presenter = Courses::ApplyPresenter.new(self, @course, @show_checkbox_recaptcha) %>

<% content_for(:head) do %>
  <title><%= presenter.page_title %></title>
  <%= stylesheet_pack_tag 'CoursesApplyPack', media: 'all' %>
<% end %>

<div class="flex min-h-screen bg-gray-100 items-center justify-center">
  <div class="py-8 w-full">
    <div class="container mx-auto px-3 max-w-lg">
      <div
        class="relative flex flex-col shadow-xl rounded-lg overflow-hidden bg-white border"
      >
        <div class="flex flex-col text-gray-900 bg-gray-200 text-white">
          <div class="relative pb-1/2 bg-primary-900">
            <% if presenter.thumbnail_url.present? %>
              <img
                class="absolute h-full w-full object-cover"
                src="<%= presenter.thumbnail_url %>"
              />
            <% else %>
              <div
                class="course-apply__cover-default absolute h-full w-full svg-bg-pattern-1"
              ></div>
            <% end %>
          </div>
        </div>
        <div>
          <div class="p-4 pt-5 md:px-12 md:py-12 md:pt-10">
            <%= form_with( url: apply_course_path(@course), method: :post, class: 'flex flex-col', local: true) do |f| %>
              <h4 class="font-bold">
                <%= t('courses.apply.heading', course_name: presenter.course_name) %>
              </h4>
              <div class="w-full">
                <div class="mt-4">
                  <label
                    for="email"
                    class="inline-block tracking-wide text-xs font-semibold"
                  >
                    <%= t('courses.apply.email_label') %>
                  </label>
                  <%= f.email_field :email, value: params[:email], maxlength: 256, placeholder: t('courses.apply.email_placeholder'), required: true, class: 'appearance-none h-10 mt-1 block w-full border border-gray-400 rounded py-2 px-4 text-sm bg-gray-100 hover:bg-gray-200 focus:outline-none focus:bg-white focus:border-primary-400' %>
                </div>
                <div class="mt-4">
                  <label
                    for="name"
                    class="inline-block tracking-wide text-xs font-semibold"
                  >
                    <%= t('courses.apply.name_label') %>
                  </label>
                  <%= f.text_field :name, value: params[:name], maxlength: 128, placeholder: t('courses.apply.name_placeholder'), required: true, class: 'appearance-none h-10 mt-1 block w-full border border-gray-400 rounded py-2 px-4 text-sm bg-gray-100 hover:bg-gray-200 focus:outline-none focus:bg-white focus:border-primary-400' %>
                </div>

                <% if @show_checkbox_recaptcha %>
                  <div class="mt-4">
                    <%=
                      recaptcha_tags(
                        site_key: ENV['RECAPTCHA_V2_SITE_KEY'],
                        nonce: content_security_policy_nonce,
                      )
                    %>
                  </div>
                <% else %>
                  <%=
                    recaptcha_v3(
                      action: 'public_course_enrollment',
                      site_key: ENV['RECAPTCHA_V3_SITE_KEY'],
                      nonce: content_security_policy_nonce,
                    )
                  %>
                <% end %>
              </div>
              <%= f.submit t('courses.apply.apply_button'), data: { disable: true }, class: "btn btn-primary btn-large text-center w-full mt-6" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="text-center mt-4 text-gray-700">
        <% if presenter.terms_and_conditions? %>
          <a
            href="/agreements/terms-and-conditions"
            class="text-xs cursor-pointer hover:text-primary-500"
          >
            <%= t('shared.terms_and_conditions') %>
          </a>
        <% end %>
        <% if presenter.terms_and_conditions? && presenter.privacy_policy? %>
          <span class="px-4 text-gray-500">&vert;</span>
        <% end %>
        <% if presenter.privacy_policy? %>
          <a
            href="/agreements/privacy-policy"
            class="text-xs cursor-pointer hover:text-primary-500"
          >
            <%= t('shared.privacy_policy') %>
          </a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/courses/curriculum.html.erb
<% content_for(:head) do %>
  <title><%= @presenter.page_title %></title>
  <%= stylesheet_pack_tag 'CoursesCurriculumPack', media: 'all' %>
<% end %>

<% content_for(:tail) do %>
  <%= javascript_pack_tag 'CoursesCurriculumPack', nonce: true %>
<% end %>

<% content_for(:inner_wrapper) do %>
  <script id="react-root-data" type="application/json"><%= @presenter.props_to_json.html_safe %></script>
  <div id="react-root"></div>
<% end %>

app/views/courses/report.html.erb
<% presenter = Courses::ReportPresenter.new(self, @course) %>

<% content_for(:head) do %>
  <title><%= presenter.page_title %></title>
  <%= stylesheet_pack_tag 'CoursesReportPack', media: 'all' %>
<% end %>

<% content_for(:tail) do %>
  <%= javascript_pack_tag 'CoursesReportPack', nonce: true %>
<% end %>


<% content_for(:inner_wrapper) do %>
  <script id="course-student-report__props" type="application/json"><%= presenter.props_to_json.html_safe %></script>
  <div id="react-root"></div>
<% end %>

app/views/courses/show.html.erb
<% presenter = Courses::ShowPresenter.new(self, @course) %>
<% content_for(:head) do %>
  <title><%= presenter.page_title %></title>
  <%= stylesheet_pack_tag 'courses/shared', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'courses/show', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'shared/markdownBlockCSS', 'data-turbolinks-track': 'reload' %>
<% end %>
<div class="pb-8 bg-gray-100 ">
  <div class="relative bg-primary-900">
    <div class="relative pb-1/2 md:pb-1/4 2xl:pb-1/5">
      <% if presenter.cover_image.present? %>
        <img
          class="absolute h-full w-full object-cover"
          src="<%= presenter.cover_image %>"
        />
      <% else %>
        <div
          class="course-show__cover-default absolute h-full w-full svg-bg-pattern-1"
        ></div>
      <% end %>
    </div>
  </div>
  <div class="px-3">
    <div class="flex flex-col md:flex-row lg:max-w-5xl mx-auto">
      <div class="flex-1">
        <div
          class="course-show__header-cta-container bg-white border-transparent shadow rounded-lg -mt-5 md:-mt-7 z-10 relative pt-4 pb-5 md:py-8"
        >
          <div class="flex md:flex-row flex-col">
            <div class="px-4 md:px-8 w-full">
              <h1 class="font-bold leading-snug">
                <%= @course.name %>
              </h1>
              <div class="mt-2">
                <%= @course.description %>
              </div>
            </div>
            <% if @course.public_preview? && @course.highlights.empty? %>
              <div
                class="w-full md:w-1/3 flex justify-center items-center mt-4 md:mt-0 px-4 md:px-8"
              >
                <a
                  href="<%= curriculum_course_path(@course) %>"
                  class="btn btn-primary btn-large w-full"
                >
                  <%= presenter.user_is_student? ? t('courses.show.continue_course') : t('courses.show.preview_course') %>
                </a>
              </div>
            <% end %>
            <% if @course.public_signup && @course.highlights.empty? %>
              <div
                class="w-full md:w-1/3 flex justify-center items-center mt-4 md:mt-0 px-4 md:px-8"
              >
                <a
                  href="<%= apply_course_path(@course) %>"
                  class="btn btn-success btn-large w-full"
                >
                  Apply Now
                </a>
              </div>
            <% end %>
          </div>
        </div>
        <div class="mt-4">
          <% if presenter.show_about? %>
            <div class="max-w-3xl mx-auto relative z-10 pb-6 md:pb-8">
              <div
                class="px-4 md:px-8 markdown-block markdown-block__permissive"
              >
                <%= sanitize(presenter.about) %>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <% if @course.highlights.present? %>
        <div class="md:ml-4 md:w-2/6 flex flex-col justify-between">
          <div
            class="py-4 md:py-6 bg-white border-transparent shadow rounded-lg md:-mt-7 z-10 relative md:sticky md:top-0"
          >
            <div class="space-y-6 px-4 md:px-6">
              <% @course.highlights.map do |highlight| %>
                <div class="flex">
                  <div class="w-12">
                    <div
                      class="flex items-center justify-center h-10 w-10 shadow bg-primary-100 text-primary-400 rounded-full p-2"
                    >
                      <i class="<%="if text-lg i-#{highlight['icon']}"%>"></i>
                    </div>
                  </div>
                  <div class="ml-2">
                    <div class="text-sm font-bold">
                      <%= highlight['title']%>
                    </div>
                    <div class="text-xs">
                      <%= highlight['description']%>
                    </div>
                  </div>
                </div>
              <%end%>
            </div>
            <% if @course.public_preview? %>
              <div class="p-4 pb-0 md:p-6 md:pb-0">
                <a
                  href="<%= curriculum_course_path(@course) %>"
                  class="btn btn-primary btn-large w-full"
                >
                  <%= presenter.user_is_student? ? t('courses.show.continue_course') : t('courses.show.preview_course') %>
                </a>
              </div>
            <% end %>
            <% if @course.public_signup %>
              <div class="p-4 pb-0 md:p-6 md:pb-0">
                <a
                  href="<%= apply_course_path(@course) %>"
                  class="btn btn-success btn-large w-full"
                >
                  Apply Now
                </a>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="hidden md:block max-w-5xl mx-auto">
      <% if @course.public_signup %>
        <div
          class="course-show__footer-cta-container bg-white py-12 px-4 text-center mt-8 border-transparent shadow rounded-lg"
        >
          <h2 class="text-3xl leading-tight">
            <span class="font-normal"> Enroll to </span>
            <span class="block font-bold">
              <%= @course.name %>
            </span>
          </h2>
          <a
            href="<%= apply_course_path(@course) %>"
            class="btn btn-large btn-success w-full sm:w-auto course-show__footer-cta-button shadow mt-3"
            >Apply Now</a
          >
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/courses/students.html.erb
<% presenter = Courses::StudentsPresenter.new(self, @course) %>
<% content_for(:head) do %>
  <title><%= presenter.page_title %></title>
  <%= stylesheet_pack_tag 'CoursesStudentsPack', media: 'all' %>
<% end %>

<% content_for(:tail) do %>
  <%= javascript_pack_tag 'CoursesStudentsPack', nonce: true %>
<% end %>

<% content_for(:inner_wrapper) do %>
  <script id="school-course-students__props" type="application/json"><%= presenter.props_to_json.html_safe %></script>
  <div id="react-root"></div>
<% end %>